"""
Problem 2: Even Fibonacci Numbers

Published on: Friday 19th October 2001, 06:00 pm
Solved by: 782702
Difficulty Rating: 5%

Problem Description:
-------------------
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

Example:
--------
Example input and output.

Input: 10
Output: 44 (2 + 8 + 34)

Solution:
---------

The goal is to find the sum of all the even Fibonacci numbers below a given value F.

We will make use of the following mathematical properties:
- The sum of the first n Fibonacci numbers is given by F(n + 2) - 1
- Every third Fibonacci number is even

Which gives the following identity:
- sum_even(F(n)) = sum(F(n)) / 2 = (F(n + 2) - 1) / 2

Where n must be a multiple of 3. Hence we need to make sure we round down n 
to the nearest multiple of 3 before computing the sum. We will do this by subtracting n mod 3.

Futhermore, we will use the formula given on the Wikipedia page for Fibonacci numbers
to compute the index of the first Fibonacci number smaller than F.
(source: https://en.wikipedia.org/wiki/Fibonacci_number#Computation_by_rounding)

n_largest(F) = floor(log(ϕ * F * sqrt(5)) / log(ϕ)) - 1

Where ϕ is the golden ratio (ϕ = (1 + sqrt(5)) / 2).

This solution method has complexity O(1), because the number of operations is constant for any F.

The solution gives: 
`solve_problem(Int64(4e6)) = 4613732`
"""

from math import floor, log, sqrt

# Golden ratio
ϕ = (1 + sqrt(5)) / 2


def n_largest(F: float) -> int:
    """
    Index of the largest Fibonacci number smaller than the number F

    :param F: Any positive number >= 1
    :return: Integer index >= 1
    """
    return floor(log(ϕ * F * sqrt(5)) / log(ϕ)) - 1


def fibonacci(n: int) -> int:
    """
    Calculate n-th Fibonacci number

    :param n: Index of the Fibonacci number to compute
    :return: n-th Fibonacci number
    """
    return floor((ϕ**n - (-ϕ) ** (-n)) / (2 * ϕ - 1))


def sum_even_fibonacci(F: float) -> int:
    """
    Sum of all the even Fibonacci numbers below F (F not included)

    :param F: Any positive number >= 1
    :return: Integer sum
    """
    if F < 1:
        raise ValueError("F must be a positive number >= 1")

    # find the index of the largest Fibonacci number smaller than F
    n = n_largest(F)

    # round down n to the nearest multiple of 3
    n -= n % 3

    # compute the sum of all the even Fibonacci numbers below n
    result = (fibonacci(n + 2) - 1) // 2
    if result < 0:
        raise ValueError("Result can't be negative")
    if result % 2 != 0:
        raise ValueError("Result must be even (sum of even numbers is even)")
    if result % 1 != 0:
        raise ValueError("Result must be an integer")
    return result


# Test the solution with the given example
print(f"Solution for F=4e6: {sum_even_fibonacci(4e6)}")
