"""
Problem 12: Highly Divisible Triangular Number

Published on: 8th March 2002 at 06:00 pm [Server Time]
Solved by: 234216
Difficulty Rating: 5%

Problem Description:
-------------------

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over n divisors?

Solution:
---------

"""

function count_divisors(x::Int64)
    """
    Count the number of divisors of x
    """
    count = 0
    for i in 1:floor(Int64, sqrt(x))
        if x % i == 0
            @show i
            count += 2
        end
    end
    return count
end


function solve_problem(n::Int64=500)
    """
    Solve the problem for a given number n
    """
    triangle = 0
    i = 1

    while true
        triangle += i
        if count_divisors(triangle) > n
            return triangle
        end
        i += 1
    end

end

# Test the solution with the given example
solve_problem()
